# upstream php_service {
#  server auxilio_php:9000;
# }

server {
    listen 80;
    server_name 10.90.20.99;
    index index.php index.html;
    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
    root /var/www/html/public;
    # autoindex on;

    # Aumentar el tamaño máximo de la solicitud a 20 MB
    client_max_body_size 100M;  # Ajusta el tamaño según tus necesidades

    location / {
        try_files $uri $uri/ /index.php?$query_string;
        gzip_static on;
    }

    location ~ \storage {
        root "/var/www/html/public/storage/";
    }

    location ~ \.php$ {
        #try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        #fastcgi_pass php_service;
        fastcgi_pass oac_laravel_dev:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        # client_max_body_size 500M;  # Esta línea no es necesaria aquí si ya está en el bloque server
    }

    #http {
    #  disable_symlinks off;
    #}
}
